version: 2

defaults: &linux_defaults
  docker:
    - image: circleci/python:3.7.2

jobs:
  check_dependencies:
    <<: *linux_defaults
    steps:
      - checkout
      - run: sudo make setup_dependencies check_dependencies

  check_links:
    <<: *linux_defaults
    steps:
      - checkout
      - run: sudo make setup_dependencies check_links

  check_syntax:
    <<: *linux_defaults
    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - run: sudo apt-get update && sudo apt-get -y install nodejs npm golang-go && sudo npm install codedown coffeescript -g
      - run: make check_syntax

workflows:
  version: 2
  test-suite:
    jobs:
      - check_dependencies
      - check_links
      - check_syntax
