version: 2

defaults: &linux_defaults
  docker:
    - image: circleci/python:3.7.2

jobs:
  setup_dependencies:
    <<: *linux_defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - makefile-{{ checksum "Makefile" }}
      - run: sudo pip install networkx matplotlib
      - save_cache:
          key: makefile-{{ checksum "Makefile" }}
          paths:
            - "/usr/lib/python3.7"
            - "/usr/local/lib/python3.7"

  check_dependencies:
    <<: *linux_defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - makefile-{{ checksum "Makefile" }}
      - run: python ./scripts/check-dependencies.py

  check_links:
    <<: *linux_defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - makefile-{{ checksum "Makefile" }}
      - run: python ./scripts/check-links.py

workflows:
  version: 2
  test-suite:
    jobs:
      - setup_dependencies:
          filters:
            tags:
              only:
                - /^v.*/
      - check_dependencies:
          requires:
            - setup_dependencies
      - check_links:
          requires:
            - setup_dependencies
