name:                transform
version:             0.1.0.0
homepage:            https://github.com/cosmos/ics
license:             BSD3
author:              Christopher Goes
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - text
  - pandoc
  - pandoc-types

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude

executables:
  spec-transform:
    source-dirs:      src
    main:             Main.hs
